### ISSUE TITLE
Not being able to run the server code even after successfully building it

### ISSUE THREAD

**Issue by rishavghosh605** [adamrehn/websocket-server-demo#1]
I went through the commands as you said and a vs solution folder was created on opening that I pressed run option(Local windows debugger)) but there was one problem , no errors one warning but on running the code wanted a file called ALL_BUILD in the server/Debug folder but there was no such file or exe there.

Can you please help me out?

**Comment by adamrehn** [comment]
The ALL_BUILD target is [automatically generated by CMake](https://stackoverflow.com/a/27175822) and is not the target for the server executable itself. **The target you want to run is called "server".** You can set this as the default target for debugging by right-clicking on it and selecting "Set as StartUp Project":

![Screenshot of setting the server target as the startup project](https://user-images.githubusercontent.com/3490860/59413711-6d38dd00-8e03-11e9-8167-243b09b1a454.png)

**Comment by rishavghosh605** [comment]
Sorry for not replying earlier, I will check back with if I have further issues

**Comment by rishavghosh605** [comment]
![image](https://user-images.githubusercontent.com/47952161/59418665-0b6a7a00-8de7-11e9-887e-2389ab36b4ae.png)
I followed the steps, and set server as the startup project but I got the following error.
I built the files by going to Developer Command Prompt for Visual Stdio
went to the server folder and typed the command:
cmake .
cmake --build .
one after the other
do I need to add any path variables before doing that?
I am using cmake version 3.14.19050301-MSVC_2

Please could you give it a look

**Comment by rishavghosh605** [comment]
![image](https://user-images.githubusercontent.com/47952161/59419217-0ce87200-8de8-11e9-9f59-86b93df148e0.png)
Error on the client side

**Comment by adamrehn** [comment]
The error message from the server tells you exactly what is wrong: `asio listen error: asio.system:10048 (Only one usage of each socket address (protocol/network address/port) is normally permitted.)`

Another process is already listening on port 8080, which is preventing the server from binding to that port. You will need to identify and terminate the other process to free the port for use by the server.

**Comment by rishavghosh605** [comment]
Cool sorry I will check it out

**Comment by rishavghosh605** [comment]
![image](https://user-images.githubusercontent.com/47952161/59442470-eb9f7a00-8e17-11e9-9c2d-904a5706596c.png)

Hey, I killed the process that was using up port 8080 - TSLNSR.exe using taskkill.
Then, I ran VS and compiled built the code having server as startup project.
But now what happens is that the exe files runs and stops instantaneously and it gets deleted from the debug folder by itself. After which on compiling again I get the error:
LNK1104	cannot open file.
![image](https://user-images.githubusercontent.com/47952161/59442857-aaf43080-8e18-11e9-9b90-6cc973455f7b.png)
 
@adamrehn  sorry to bother you once again, but I really need this to work.

**Comment by rishavghosh605** [comment]
Hey it worked , I was initially having some problems with the exe file cause of Avast Antivirus on stopping it I got the following output:
![image](https://user-images.githubusercontent.com/47952161/59445418-425b8280-8e1d-11e9-8617-637d666ce011.png)

So the sockets are connecting and server is sending messages to the clients.
But on hitting send message on the client side  I am not able to see if I have recieved  {"a":1, "b":2, "c":3} or not. How will I know the above?

@adamrehn sorry for bombarding you with problems,  but I really need this to work.
Thanks a lot for your help till now.

**Comment by adamrehn** [comment]
It's been years since I last looked through the code for this demo, so on initial inspection I was actually just as confused as you regarding the lack of feedback for sent messages. Having looked through the code now, I've realised that there's actually a discrepancy between the code in this repository and the workshop that it was written for.

In this repo, I've hard-coded the server to [listen for messages with a type of `myMessage`](https://github.com/adamrehn/websocket-server-demo/blob/master/server/server.cpp#L36), but in the original workshop the server [listens for messages with a type of `message`](https://github.com/club-plus-plus/websocket-server-workshop/blob/master/Part4.md#multiple-event-loops), which is what the client sends by default. Messages with this type are ignored, but if you enter `myMessage` in the text field on the client then the messages will be acknowledged correctly and echoed back to the client.

I'm not entirely sure how this discrepancy crept in. Presumably I must've made that change at some point during the workshop to demonstrate the handler functionality for the students, and then forgotten to change it back before uploading the code.

**Comment by adamrehn** [comment]
I've pushed a fix for this now, which realigns the code in this repository with the workshop notes. Thanks for helping to uncover this oversight!

**Comment by rishavghosh605** [comment]
Yeah no problem, and thanks to you too. Without your demo code it would have been impossible to build the code from the websocketpp repo as I  had no idea of what files to link to make the repo examples work.

**Comment by rishavghosh605** [comment]
Hi, @adamrehn  ,had a query:
Do you have any idea how to build the projects in the https://github.com/zaphoyd/websocketpp directory just wanted to build those examples to see how to configure your demo, or is there a way to compile those using your demo?

**Comment by adamrehn** [comment]
@rishavghosh605 that question is best directed to the maintainers of the WebSocket++ library itself, since my demo doesn't use their examples.

**Comment by rishavghosh605** [comment]
Hey @adamrehn  had a question simple question bout your demo, when I use cmake and build the project I am able to access the exe file. But if I copy this same exe to another computer which does not have Visual Studio. On  opening the ex file on another latop I get the error : the code execution could not be done because MSVCP140D.dll, VCRUNTIME!$)D.dll and ucrtbased.dll was not found. So I copied all of these files from my computer, and also downloded the redistributable C++  packages, but still the problem did not go. 

Is it because I have not downloaded anything, or I have to build the files on the other laptop using cmake?

I was hoping you could shed some light on it.

Sorry, for disturbing you once again, but I promise this will be the last time.

**Comment by adamrehn** [comment]
@rishavghosh605 if you're building any C++ project with Visual Studio for use on another computer then you should build the Release configuration and ensure the target machine has the Visual C++ Redistributable package installed that corresponds to the version of Visual Studio that you used to build the executable. You can find the relevant documentation here: <https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute>

Again, this is a question that is not specific to my demo code, and is therefore best asked in a more appropriate venue. I'm locking this thread now to prevent any further discussion. If you have any further questions that are specifically related to the WebSocket demo code then feel free to open separate issues to address those questions.
