### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ottmar-zittlau** [adamrehn/websocket-server-demo#2]
Hi,

first of all - thanks for the nice example.

When I try to build the server example I get the following error:
`/usr/include/c++/9/thread:126: Fehler: undefined reference to 'pthread_create'`

I manage to fix it by adding the threads library explicitly to the cmake-file (following https://stackoverflow.com/questions/30734136/cmake-linking-error-pthread-enable-multithreading-to-use-stdthread-operation):
```
find_package (Threads)

# Build the server executable
add_executable(server server.cpp WebsocketServer.cpp)
target_link_libraries (server jsoncpp)
target_link_libraries (server Threads::Threads)
```
Is this the way to go, or should I configure it somehow differently?
I'm using Ubuntu 20.04.

Thanks in advance!
oz

**Comment by melnarte** [comment]
@ottmar-zittlau would you like to provide your complete CMake-file, please.

**Comment by adamrehn** [comment]
Wow, I'm amazed that people are still using this old demo. In keeping with the age of the codebase, I've implemented the fix using the method I would've used back when I first wrote it (which was before I knew CMake import targets existed.) It's definitely not the optimal way of doing it, but I feel it's fitting in this particular context.
